### ISSUE TITLE
Addition of corresponding raw functions

### ISSUE THREAD

**Issue by pranshi06** [MichelBoucey/gothic#1]
Some function like [`getSecretR`](https://hackage.haskell.org/package/gothic-0.1.8/docs/src/Database.Vault.KVv2.Client.Requests.html#getSecretR) uses separate "vault-address, kvEngine-path, secret-path". I was wondering if it is possible to have simpler corresponding functions e.g., a `getSecretRaw` which takes the entire path and process it. These Raw functions can be used inside the original functions so that it does not break the current implementation and adds another way to use the arguments.
Let me know your thoughts on it. Thanks.

**Comment by MichelBoucey** [comment]
Look closely to signatures of those functions. They don't use separately "vault-address, kvEngine-path, secret-path". Those are inside a type named `SecretPath`. I think I have done things the Haskell way. But If you need much raw signatures, feel free to use `Types` and `Internals` functions to build your own functions. I don't feel the need of those signatures for this library.
